#!/usr/bin/env ruby

# Trap ^C
Signal.trap("INT") {
  puts "\nCtrl-C detected. Exiting..."
  sleep 1
  exit
}

$:.unshift(File.expand_path("../../lib", __FILE__))
require "ticktok-cli"
require "ticktok_cli/cli"

TicktokCli::CLI.start(ARGV)
